# Generated by Django 4.2.1 on 2023-05-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='youssef', max_length=50),
            preserve_default=False,
        ),
    ]
