# Generated by Django 4.2.1 on 2023-05-30 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
