# Generated by Django 4.2.1 on 2023-05-30 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_property_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date_posted',
            field=models.DateField(default=datetime.date(2023, 5, 30)),
        ),
    ]
