# Generated by Django 4.2.1 on 2023-06-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_rename_seller_property_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='user',
            new_name='seller',
        ),
    ]
