# Generated by Django 4.2.1 on 2023-06-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='seller',
        ),
    ]
